# Generated by Django 2.0.2 on 2018-04-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('entry_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_store', models.CharField(max_length=255)),
                ('product_link', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
