# Generated by Django 2.0.2 on 2018-04-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='product_post',
        ),
    ]
