# Generated by Django 2.0.2 on 2018-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180420_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_post',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
