# Generated by Django 2.0.2 on 2018-04-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180420_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_post',
            name='user',
        ),
    ]
