# Generated by Django 2.0.2 on 2018-04-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_post',
            name='user',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
