# Generated by Django 2.0.2 on 2018-05-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180501_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='nickname',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='account',
            name='lname',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
