# Generated by Django 2.0.2 on 2018-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180501_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_post',
            old_name='user',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='product_post',
            name='lname',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
