# Generated by Django 2.0.2 on 2018-05-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180501_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_post',
            name='user',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
